server:
  port: 11002

logging:
  config: classpath:log4j2.yml

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.10:3306/demo?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
